"""Untouched test evaluation, physical diagnostics, timing and grid transfer."""
import argparse
import json
import platform
from pathlib import Path
from time import perf_counter
import numpy as np
import torch
from .data import initial_conditions, relative_errors
from .models import build_model
from .solver import grid, heat_solution, solve, upsample_periodic
from .train import seed_everything


def metrics(pred, target, initial):
    relative = relative_errors(pred, target)
    mean_drift = np.abs(pred.mean(axis=-1)-initial.mean(axis=-1))
    energy_gain = np.mean(pred**2, axis=-1)-np.mean(initial**2, axis=-1)
    return {
        'mean_relative_l2':float(relative.mean()), 'median_relative_l2':float(np.median(relative)),
        'p95_relative_l2':float(np.quantile(relative, 0.95)), 'worst_relative_l2':float(relative.max()),
        'mse':float(np.mean((pred-target)**2)), 'mae':float(np.mean(np.abs(pred-target))),
        'max_abs_mean_drift':float(mean_drift.max()),
        'energy_increase_fraction':float(np.mean(energy_gain > 1e-6)),
        'max_energy_increase':float(max(0, energy_gain.max())),
    }


def predict(model, x, batch_size):
    outputs = []
    model.eval()
    with torch.inference_mode():
        for offset in range(0, len(x), batch_size):
            batch = torch.from_numpy(x[offset:offset+batch_size].astype('float32')).unsqueeze(1)
            outputs.append(model(batch).squeeze(1).numpy())
    return np.concatenate(outputs)


def timed_prediction(model, x, batch_size):
    predict(model, x, batch_size)  # warm-up excluded from timing
    times = []
    for _ in range(5):
        start = perf_counter()
        result = predict(model, x, batch_size)
        times.append(perf_counter()-start)
    return result, float(np.median(times))


def load_model(path):
    # Only load checkpoints generated by this project from trusted local paths.
    checkpoint = torch.load(path, map_location='cpu', weights_only=True)
    model = build_model(checkpoint['model'], checkpoint['config'])
    model.load_state_dict(checkpoint['state_dict'])
    return model, checkpoint


def evaluate(data_path, run_dir):
    data_path, run_dir = Path(data_path), Path(run_dir)
    metadata = json.loads(data_path.with_suffix('.json').read_text())
    config = metadata['config']
    seed_everything(config['seed'], config['threads'])
    with np.load(data_path) as data:
        test_indices = data['test'].copy()
        x, y = data['x'][test_indices].copy(), data['y'][test_indices].copy()
        coeff = data['coefficients'][test_indices[:config['resolution_samples']]].copy()
    models = {}
    for name in ['fno', 'cnn']:
        model, checkpoint = load_model(run_dir/f'{name}.pt')
        if checkpoint['config'] != config:
            raise ValueError('Checkpoint and dataset configurations differ')
        models[name] = model
    predictions = {'identity':x, 'heat':heat_solution(x, config['viscosity'], config['time'])}
    report = {'config':config, 'test_samples':len(x), 'solver_verification':metadata['solver_verification'],
              'hardware':{'platform':platform.platform(), 'processor':platform.processor(),
                          'torch':str(torch.__version__), 'device':'cpu', 'threads':config['threads']},
              'dataset_generation_seconds':metadata['generation_seconds'], 'test':{}, 'resolution_transfer':[]}
    for name, model in models.items():
        predictions[name], seconds = timed_prediction(model, x, config['batch_size'])
        training = json.loads((run_dir/f'{name}_training.json').read_text())
        report['test'][name] = {'prediction_seconds':seconds, 'seconds_per_sample':seconds/len(x),
                              'training_seconds':training['training_seconds'], 'parameters':training['parameters']}
    for name, prediction in predictions.items():
        report['test'].setdefault(name, {}).update(metrics(prediction, y, x))
    report['reference_physics'] = metrics(y, y, x)
    # Accuracy/runtime curve on the same held-out functions at training resolution.
    # Include cheap coarse solves rather than claiming the finest solver is the
    # only alternative to approximate neural inference.
    report['solver_accuracy_runtime'] = []
    benchmark_n = config['grid_points']
    benchmark_initial = initial_conditions(coeff, benchmark_n)
    benchmark_target = y[:len(coeff)]
    for solver_n in [n for n in [32, 64, 128, 256] if n <= benchmark_n and config['initial_modes'] < n/3]:
        solver_input = initial_conditions(coeff, solver_n)
        solve(solver_input, config['viscosity'], config['time'], config['cfl'])
        timings = []
        for _ in range(3):
            start = perf_counter()
            result = upsample_periodic(solve(solver_input, config['viscosity'], config['time'], config['cfl']), benchmark_n)
            timings.append(perf_counter()-start)
        report['solver_accuracy_runtime'].append({'solver_points':solver_n, 'samples':len(coeff),
            'prediction_seconds':float(np.median(timings)), **metrics(result, benchmark_target, benchmark_initial)})
    for n in config['evaluation_resolutions']:
        reference_n = max(2*n, config['reference_points'])
        if reference_n % n:
            raise ValueError('Resolution must divide its reference grid')
        initial = initial_conditions(coeff, n)
        reference_initial = initial_conditions(coeff, reference_n)
        start = perf_counter()
        target = solve(reference_initial, config['viscosity'], config['time'], config['cfl'])[:, ::reference_n//n]
        solver_seconds = perf_counter()-start
        # Check grid/time accuracy on exactly the benchmark cases, outside timing.
        checked_target = solve(reference_initial, config['viscosity'], config['time'], config['cfl']/2)[:, ::reference_n//n]
        target_time_error = float(relative_errors(target, checked_target).max())
        finer = solve(initial_conditions(coeff, 2*reference_n), config['viscosity'], config['time'], config['cfl'])[:, ::2*reference_n//n]
        target_grid_error = float(relative_errors(target, finer).max())
        if max(target_time_error, target_grid_error) >= config['solver_tolerance']:
            raise RuntimeError('Resolution benchmark reference failed grid/time convergence')
        row = {'grid_points':n, 'reference_points':reference_n, 'samples':len(coeff),
               'reference_solver_seconds':solver_seconds, 'reference_time_error':target_time_error,
               'reference_grid_error':target_grid_error, 'models':{}}
        for name, model in models.items():
            pred, seconds = timed_prediction(model, initial, config['batch_size'])
            row['models'][name] = {**metrics(pred, target, initial), 'prediction_seconds':seconds,
                                  'speedup_vs_reference_solver':solver_seconds/seconds}
        report['resolution_transfer'].append(row)
    (run_dir/'metrics.json').write_text(json.dumps(report, indent=2)+'\n')
    make_plots(x, y, predictions, run_dir, report)
    make_report(report, run_dir)
    print((run_dir/'report.md').read_text())
    return report


def make_plots(x, y, predictions, run_dir, report):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    errors = relative_errors(predictions['fno'], y)
    indices = [int(np.argsort(errors)[len(errors)//2]), int(errors.argmax())]
    fig, axes = plt.subplots(1, 2, figsize=(12, 4), constrained_layout=True)
    for ax, index, label in zip(axes, indices, ['Median-error case', 'Worst-error case']):
        ax.plot(grid(x.shape[-1]), x[index], '--', color='gray', label='Initial')
        ax.plot(grid(x.shape[-1]), y[index], color='black', label='Solver target')
        for name in ['fno', 'cnn', 'heat']:
            ax.plot(grid(x.shape[-1]), predictions[name][index], label=name.upper())
        ax.set(xlabel='Position x', ylabel='u(x,T)', title=f'{label}: FNO error {errors[index]:.1%}')
        ax.legend(fontsize=8)
    fig.savefig(run_dir/'predictions.png', dpi=160)
    plt.close(fig)
    fig, axes = plt.subplots(1, 2, figsize=(12, 4), constrained_layout=True)
    for name in ['fno', 'cnn']:
        history = json.loads((run_dir/f'{name}_training.json').read_text())['history']
        axes[0].plot([h['epoch'] for h in history], [h['train_relative_l2'] for h in history], '--', label=f'{name} train')
        axes[0].plot([h['epoch'] for h in history], [h['validation_relative_l2'] for h in history], label=f'{name} validation')
        rows = report['resolution_transfer']
        axes[1].plot([r['grid_points'] for r in rows], [r['models'][name]['mean_relative_l2'] for r in rows], 'o-', label=name)
    axes[0].set(xlabel='Epoch', ylabel='Relative L2 error', yscale='log', title='Training and validation')
    axes[1].set(xlabel='Evaluation grid points', ylabel='Mean relative L2 error', title='Same held-out waves, no retraining')
    for ax in axes:
        ax.legend()
        ax.grid(alpha=0.2)
    fig.savefig(run_dir/'learning_and_resolution.png', dpi=160)
    plt.close(fig)


def make_report(report, run_dir):
    lines = ['# Measured experiment results', '',
             f"CPU run; {report['test_samples']} untouched test cases; seed {report['config']['seed']}.", '',
             '| Model | Mean relative L2 | Median | 95th percentile | Worst |',
             '|---|---:|---:|---:|---:|']
    for name, m in report['test'].items():
        lines.append(f"| {name} | {m['mean_relative_l2']:.2%} | {m['median_relative_l2']:.2%} | {m['p95_relative_l2']:.2%} | {m['worst_relative_l2']:.2%} |")
    lines += ['', '## Resolution transfer', '',
              '| Grid | Cases | FNO error | CNN error | FNO speedup vs reference solver |',
              '|---|---:|---:|---:|---:|']
    for row in report['resolution_transfer']:
        lines.append(f"| {row['grid_points']} | {row['samples']} | {row['models']['fno']['mean_relative_l2']:.2%} | {row['models']['cnn']['mean_relative_l2']:.2%} | {row['models']['fno']['speedup_vs_reference_solver']:.1f}x |")
    lines += ['', '## Solver accuracy versus runtime', '',
              'Same held-out waves as grid transfer, evaluated at the training resolution.',
              'Solver predictions are Fourier-interpolated to that resolution; timing includes interpolation.', '',
              '| Solver grid | Mean relative L2 | Batch time (seconds) |',
              '|---|---:|---:|']
    for row in report['solver_accuracy_runtime']:
        lines.append(f"| {row['solver_points']} | {row['mean_relative_l2']:.4%} | {row['prediction_seconds']:.5f} |")
    lines += ['', 'Neural timings for the same waves are in resolution_transfer in metrics.json.',
              'Use this curve to compare accuracy and cost; a coarse numerical solve may be preferable.', '', 'Timing uses the same waves on the same CPU. Neural timing includes NumPy/tensor conversion,',
              'uses five repetitions after warm-up, and reports the median. Solver timing is one',
              'batched run on the reported finer reference grid, including downsampling.',
              'Speedup is relative to this reference solver; it is not a universal or accuracy-matched solver benchmark.',
              'Training and data generation costs are separate in metrics.json.', '',
              'Physics checks are diagnostics, not constraints imposed on the model. See metrics.json',
              'for mean drift and energy increases, full configuration, and convergence errors.', '',
              '![Median and worst predictions](predictions.png)', '',
              '![Learning curves and resolution transfer](learning_and_resolution.png)', '']
    (run_dir/'report.md').write_text('\n'.join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', default='artifacts/data.npz')
    parser.add_argument('--run', default='artifacts/run')
    args = parser.parse_args()
    evaluate(args.data, args.run)


if __name__ == '__main__':
    main()
